# Generated by Django 3.1.3 on 2020-11-06 21:20

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('apiPath', models.CharField(blank=True, max_length=200, null=True)),
                ('nodeType', models.CharField(blank=True, max_length=20, null=True)),
                ('nodeReference', models.JSONField(blank=True, null=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.node')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
