# Generated by Django 3.1.3 on 2020-11-09 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='latLngArr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, default=['70', '40'], size=None),
            preserve_default=False,
        ),
    ]
