# Generated by Django 3.1.3 on 2020-11-09 18:24

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_node_latlngarr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='latLngArr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, size=None),
        ),
    ]
