# Generated by Django 3.1.3 on 2020-11-10 03:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201110_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='latLngArr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, size=None),
        ),
    ]
