# Generated by Django 3.1.3 on 2020-11-11 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201110_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='isDir',
            field=models.BooleanField(default=False),
        ),
    ]
