# Generated by Django 3.1.3 on 2020-11-12 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_node_isdir'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='icon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
