# Generated by Django 3.1.3 on 2020-11-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_node_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='iconValue',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
