# Generated by Django 3.1.3 on 2020-11-13 17:49

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_auto_20201113_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNode',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('value', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('apiPath', models.CharField(blank=True, max_length=200, null=True)),
                ('nodeType', models.CharField(blank=True, max_length=20, null=True)),
                ('latLngArr', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, size=None)),
                ('nodeReference', models.JSONField(blank=True, null=True)),
                ('isDir', models.BooleanField(default=False)),
                ('icon', models.CharField(blank=True, max_length=30, null=True)),
                ('iconValue', models.CharField(blank=True, max_length=30, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.node')),
            ],
            options={
                'verbose_name': 'historical node',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
