# Generated by Django 3.1.3 on 2020-11-13 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20201113_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeHistory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.node',),
        ),
    ]
