# Generated by Django 3.1.3 on 2020-11-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_historicalnodehistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnodehistory',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalnodehistory',
            name='parent',
        ),
        migrations.DeleteModel(
            name='NodeHistory',
        ),
        migrations.DeleteModel(
            name='HistoricalNodeHistory',
        ),
    ]
