# Generated by Django 3.1.3 on 2020-11-16 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20201113_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnode',
            name='color',
            field=models.CharField(blank=True, default='black', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='color',
            field=models.CharField(blank=True, default='black', max_length=16, null=True),
        ),
    ]
