# Generated by Django 3.1.3 on 2020-11-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20201116_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnode',
            name='description',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='node',
            name='description',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
