# Generated by Django 3.1.3 on 2020-11-25 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201125_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnode',
            name='team',
        ),
        migrations.RemoveField(
            model_name='node',
            name='team',
        ),
    ]
