# Generated by Django 3.1.3 on 2020-11-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20201125_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='Node', to='api.Node'),
        ),
        migrations.AlterField(
            model_name='node',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team', to='api.team'),
        ),
    ]
