# Generated by Django 3.1.3 on 2020-11-25 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0019_auto_20201125_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnode',
            name='team',
        ),
        migrations.RemoveField(
            model_name='node',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='users',
        ),
        migrations.AlterField(
            model_name='team',
            name='nodes',
            field=models.ManyToManyField(blank=True, related_name='nodes', to='api.Node'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teams', models.ManyToManyField(blank=True, related_name='teams', to='api.Team')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
