# Generated by Django 3.1.3 on 2020-11-26 19:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20201125_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnode',
            name='latLngArr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='node',
            name='latLngArr',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, null=True, size=None),
        ),
    ]
