# Generated by Django 3.1.3 on 2020-11-28 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_team_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='key',
            field=models.CharField(blank=True, default='1BXRD', max_length=5, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
