# Generated by Django 3.1.3 on 2020-12-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20201207_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalnode',
            name='apiPath',
        ),
        migrations.RemoveField(
            model_name='historicalnode',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='historicalnode',
            name='nodeReference',
        ),
        migrations.RemoveField(
            model_name='node',
            name='apiPath',
        ),
        migrations.RemoveField(
            model_name='node',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='node',
            name='nodeReference',
        ),
        migrations.AlterField(
            model_name='historicalnode',
            name='value',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
