# Generated by Django 3.1.3 on 2020-12-11 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20201209_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnode',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnode',
            name='iconValue',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnode',
            name='nodeType',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnode',
            name='value',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterField(
            model_name='node',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='iconValue',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='nodeType',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='value',
            field=models.CharField(default=uuid.uuid4, max_length=64, unique=True),
        ),
    ]
