import React from "react";
import IconButton from "@material-ui/core/IconButton";
import Divider from "@material-ui/core/Divider";

const IconList = ({ handleButtonClick }) => {
  let icons = [
    "https",
    "backup",
    "vertical_align_center",
    "timelapse",
    "local_car_wash",
    "filter_4",
    "rv_hookup",
    "signal_cellular_no_sim",
    "search",
    "volume_mute",
    "swap_vertical_circle",
    "find_in_page",
    "branding_watermark",
    "do_not_disturb_off",
    "videocam_off",
    "note_add",
    "shop_two",
    "receipt",
    "payment",
    "local_post_office",
    "account_box",
    "queue",
    "system_update_alt",
    "check_box_outline_blank",
    "markunread",
    "list",
    "flip_to_front",
    "power_input",
    "add_alarm",

    "closed_caption",
    "picture_as_pdf",
    "create",
    "drive_eta",
    "camera_rear",
    "sd_storage",
    "keyboard_arrow_up",
    "local_taxi",
    "wifi_tethering",
    "filter_5",
    "airplay",
    "broken_image",
    "trending_flat",
    "forward_5",
    "blur_circular",
    "screen_lock_landscape",
    "arrow_drop_up",
    "filter_none",
    "control_point",
    "face",
    "repeat",
    "flight",
    "local_library",
    "filter_7",
    "assistant",
    "mail_outline",
    "arrow_drop_down_circle",
    "straighten",
    "border_clear",
    "stay_current_landscape",
    "perm_media",
    "reply",
    "signal_cellular_off",
    "fiber_smart_record",
    "assignment_ind",
    "perm_contact_calendar",
    "monochrome_photos",
    "bookmark_border",
    "not_interested",
    "phone_missed",
    "crop_portrait",
    "translate",
    "3d_rotation",
    "location_searching",
    "mode_comment",
    "network_wifi",
    "wb_auto",
    "hearing",
    "font_download",
    "highlight",
    "query_builder",
    "fullscreen",
    "local_activity",
    "remove_circle_outline",
    "crop_square",
    "swap_calls",
    "replay_30",
    "av_timer",
    "restaurant",
    "directions_boat",
    "color_lens",
    "tab",
    "panorama",
    "pool",
    "android",
    "directions_transit",
    "filter_6",
    "thumb_down",
    "http",
    // "volume_up",
    // "person",
    // "desktop_mac",
    // "airline_seat_recline_extra",
    // "home",
    // "shop",
    // "copyright",
    // "smartphone",
    // "flight_takeoff",
    // "directions_railway",
    // "filter_2",
    // "insert_drive_file",
    // "camera_enhance",
    // "format_align_center",
    // "eject",
    // "exposure_plus_1",
    // "forward_10",
    // "room",
    // "battery_std",
    // "local_pizza",
    // "filter_b_and_w",
    // "ring_volume",
    // "dock",
    // "local_cafe",
    // "nfc",
    // "cancel",
    // "usb",
    // "filter_drama",
    // "person_outline",
    // "mood",
    // "phone_in_talk",
    // "fast_rewind",
    // "art_track",
    // "blur_off",
    // "brightness_medium",
    // "no_encryption",
    // "report_problem",
    // "border_left",
    // "alarm_on",
    // "crop",
    // "airline_seat_individual_suite",
    // "hot_tub",
    // "photo_size_select_actual",
    // "settings_phone",
    // "filter_3",
    // "credit_card",
    // "arrow_downward",
    // "monetization_on",
    // "arrow_back",
    // "visibility",
    // "wb_cloudy",
    // "youtube_searched_for",
    // "border_outer",
    // "musnote",
    // "cloud_download",
    // "call_made",
    // "brightness_low",
    // "strikethrough_s",
    // "info_outline",
    // "filter_1",
    // "headset",
    // "label",
    // "folder_special",
    // "filter_tilt_shift",
    // "change_history",
    // "time_to_leave",
    // "map",
    // "inbox",
    // "sim_card",
    // "loupe",
    // "power",
    // "chat_bubble",
    // "mms",
    // "rss_feed",
    // "exposure_plus_2",
    // "border_all",
    // "card_travel",
    // "transform",
    // "sentiment_satisfied",
    // "do_not_disturb_on",
    // "center_focus_strong",
    // "wb_iridescent",
    // "collections_bookmark",
    // "zoom_in",
    // "sentiment_very_dissatisfied",
    // "subtitles",
    // "format_align_left",
    // "games",
    // "plus_one",
    // "devices",
    // "voicemail",
    // "clear",
    // "call_missed_outgoing",
    // "data_usage",
    // "center_focus_weak",
    // "signal_wifi_off",
    // "local_dining",
    // "event_busy",
    // "perm_identity",
    // "perm_scan_wifi",
    // "format_quote",
    // "store_mall_directory",
    // "signal_wifi_0_bar",
    // "settings_input_composite",
    // "live_help",
    // "network_locked",
    // "photo_album",
    // "notifications_off",
    // "directions_bus",
    // "zoom_out_map",
    // "cloud_done",
    // "grade",
    // "camera_roll",
    // "wrap_text",
    // "build",
    // "whatshot",
    // "keyboard",
    // "format_strikethrough",
    // "voice_chat",
    // "border_horizontal",
    // "brightness_high",
    // "lock",
    // "toys",
    // "fiber_dvr",
    // "sentiment_dissatisfied",
    // "view_comfy",
    // "portrait",
    // "developer_mode",
    // "insert_emoticon",
    // "phonelink_off",
    // "view_headline",
    // "settings_voice",
    // "developer_board",
    // "link",
    // "line_weight",
    // "dehaze",
    // "system_update",
    // "trending_up",
    // "cloud_upload",
    // "settings_remote",
    // "crop_free",
    // "surround_sound",
    // "contact_phone",
    // "access_alarm",
    // "repeat_one",
    // "phonelink",
    // "grid_on",
    // "landscape",
    // "playlist_play",
    // "store",
    // "file_download",
    // "healing",
    // "insert_photo",
    // "group_add",
    // "brush",
    // "library_books",
    // "colorize",
    // "important_devices",
    // "wallpaper",
    // "markunread_mailbox",
    // "supervisor_account",
    // "smoke_free",
    // "linear_scale",
    // "local_movies",
    // "movie_creation",
    // "dns",
    // "picture_in_picture",
    // "format_textdirection_r_to_l",
    // "phone_android",
    // "group",
    // "settings",
    // "fiber_manual_record",
    // "local_phone",
    // "last_page",
    // "account_balance",
    // "directions_car",
    // "remove_from_queue",
    // "swap_horiz",
    // "movie",
    // "archive",
    // "format_color_reset",
    // "beenhere",
    // "dialer_sip",
    // "pie_chart",
    // "polymer",
    // "screen_rotation",
    // "add_circle_outline",
    // "lens",
    // "pause_circle_filled",
    // "mail",
    // "school",
    // "title",
    // "panorama_vertical",
    // "format_underlined",
    // "view_stream",
    // "watch_later",
    // "donut_small",
    // "track_changes",
    // "note",
    // "apps",
    // "desktop_windows",
    // "filter_center_focus",
    // "directions_bike",
    // "laptop_chromebook",
    // "assignment_turned_in",
    // "keyboard_arrow_down",
    // "edit_location",
    // "details",
    // "money_off",
    // "phonelink_lock",
    // "ondemand_video",
    // "tv",
    // "sms",
    // "playlist_add",
    // "adb",
    // "location_off",
    // "turned_in",
    // "photo_size_select_large",
    // "videocam",
    // "satellite",
    // "directions_run",
    // "indeterminate_check_box",
    // "layers_clear",
    // "signal_cellular_4_bar",
    // "volume_off",
    // "layers",
    // "radio",
    // "local_laundry_service",
    // "add_location",
    // "settings_input_antenna",
    // "book",
    // "speaker_phone",
    // "fiber_pin",
    // "view_quilt",
    // "add_shopping_cart",
    // "hotel",
    // "settings_input_hdmi",
    // "donut_large",
    // "terrain",
    // "view_carousel",
    // "local_printshop",
    // "train",
    // "photo_size_select_small",
    // "error_outline",
    // "local_florist",
    // "sentiment_very_satisfied",
    // "place",
    // "casino",
    // "switch_camera",
    // "phone_forwarded",
    // "dashboard",
    // "chevron_right",
    // "tap_and_play",
    // "code",
    // "speaker_notes_off",
    // "cake",
    // "panorama_wide_angle",
    // "exposure_zero",
    // "rounded_corner",
    // "gif",
    // "cast",
    // "flag",
    // "near_me",
    // "chevron_left",
    // "pause_circle_outline",
    // "update",
    // "redeem",
    // "line_style",
    // "event_available",
    // "wb_sunny",
    // "stop",
    // "flight_land",
    // "access_time",
    // "event",
    // "settings_ethernet",
    // "remove_shopping_cart",
    // "perm_device_information",
    // "class",
    // "panorama_fish_eye",
    // "forum",
    // "account_circle",
    // "audiotrack",
    // "location_disabled",
    // "mode_edit",
    // "gps_off",
    // "skip_next",
    // "widgets",
    // "trending_down",
    // "work",
    // "view_compact",
    // "recent_actors",
    // "picture_in_picture_alt",
    // "disc_full",
    // "rotate_90_degrees_ccw",
    // "keyboard_hide",
    // "crop_landscape",
    // "crop_16_9",
    // "move_to_inbox",
    // "notifications_active",
    // "tab_unselected",
    // "live_tv",
    // "subscriptions",
    // "local_pharmacy",
    // "panorama_horizontal",
    // "border_inner",
    // "check",
    // "aspect_ratio",
    // "looks_two",
    // "cloud_queue",
    // "warning",
    // "notifications_paused",
    // "gradient",
    // "sms_failed",
    // "account_balance_wallet",
    // "low_priority",
    // "business_center",
    // "format_align_right",
    // "bluetooth",
    // "touch_app",
    // "skip_previous",
    // "call_received",
    // "space_bar",
    // "playlist_add_check",
    // "party_mode",
    // "functions",
    // "priority_high",
    // "ev_station",
    // "fast_forward",
    // "bubble_chart",
    // "lock_open",
    // "email",
    // "wifi",
    // "crop_original",
    // "timer_off",
    // "import_contacts",
    // "drafts",
    // "watch",
    // "create_new_folder",
    // "info",
    // "compare_arrows",
    // "domain",
    // "shopping_cart",
    // "today",
    // "local_atm",
    // "select_all",
    // "invert_colors",
    // "palette",
    // "replay",
    // "find_replace",
    // "text_format",
    // "add",
    // "present_to_all",
    // "directions",
    // "dvr",
    // "video_call",
    // "personal_video",
    // "arrow_upward",
    // "movie_filter",
    // "bluetooth_audio",
    // "first_page",
    // "local_gas_station",
    // "close",
    // "show_chart",
    // "people",
    // "more_horiz",
    // "toll",
    // "dialpad",
    // "airplanemode_active",
    // "call_missed",
    // "keyboard_arrow_left",
    // "screen_lock_rotation",
    // "crop_7_5",
    // "looks_3",
    // "view_day",
    // "pages",
    // "star_border",
    // "card_giftcard",
    // "all_inclusive",
    // "exposure_neg_2",
    // "invert_colors_off",
    // "check_circle",
    // "tram",
    // "snooze",
    // "keyboard_backspace",
    // "subject",
    // "location_city",
    // "laptop_mac",
    // "wifi_lock",
    // "bluetooth_disabled",
    // "volume_down",
    // "refresh",
    // "opacity",
    // "launch",
    // "tag_faces",
    // "local_shipping",
    // "free_breakfast",
    // "person_pin_circle",
    // "exit_to_app",
    // "compare",
    // "image",
    // "euro_symbol",
    // "directions_walk",
    // "content_cut",
    // "attach_money",
    // "view_list",
    // "view_array",
    // "save",
    // "navigation",
    // "favorite",
    // "keyboard_return",
    // "filter_hdr",
    // "swap_vert",
    // "arrow_drop_down",
    // "replay_5",
    // "phone_iphone",
    // "gps_not_fixed",
    // "crop_5_4",
    // "navigate_before",
    // "format_indent_increase",
    // "folder_shared",
    // "leak_remove",
    // "crop_din",
    // "flash_on",
    // "content_copy",
    // "device_hub",
    // "airplanemode_inactive",
    // "exposure_neg_1",
    // "gesture",
    // "pan_tool",
    // "open_in_browser",
    // "library_add",
    // "message",
    // "do_not_disturb_alt",
    // "subdirectory_arrow_left",
    // "call_to_action",
    // "hdr_on",
    // "alarm_add",
    // "restore_page",
    // "leak_add",
    // "style",
    // "crop_3_2",
    // "wb_incandescent",
    // "phone_locked",
    // "local_drink",
    // "report",
    // "format_color_text",
    // "perm_data_setting",
    // "chat",
    // "phonelink_erase",
    // "local_mall",
    // "child_friendly",
    // "filter_frames",
    // "send",
    // "blur_linear",
    // "record_voice_over",
    // "expand_more",
    // "speaker",
    // "play_circle_outline",
    // "explore",
    // "publish",
    // "bug_report",
    // "network_cell",
    // "feedback",
    // "screen_lock_portrait",
    // "card_membership",
    // "camera",
    // "rotate_left",
    // "confirmation_number",
    // "assignment_return",
    // "redo",
    // "chat_bubble_outline",
    // "stars",
    // "assignment",
    // "settings_input_svideo",
    // "play_for_work",
    // "merge_type",
    // "battery_alert",
    // "loop",
    // "power_settings_new",
    // "looks_5",
    // "settings_system_daydream",
    // "bluetooth_connected",
    // "security",
    // "more",
    // "alarm_off",
    // "stay_current_portrait",
    // "insert_chart",
    // "speaker_notes",
    // "rate_review",
    // "spellcheck",
    // "ac_unit",
    // "iso",
    // "video_label",
    // "thumb_up",
    // "crop_rotate",
    // "border_right",
    // "textsms",
    // "video_library",
    // "filter_9_plus",
    // "flare",
    // "attachment",
    // "transfer_within_a_station",
    // "border_vertical",
    // "child_care",
    // "unfold_more",
    // "call_split",
    // "directions_subway",
    // "signal_cellular_0_bar",
    // "filter_vintage",
    // "format_textdirection_l_to_r",
    // "bluetooth_searching",
    // "memory",
    // "flash_off",
    // "contacts",
    // "collections",
    // "accessible",
    // "looks_4",
    // "pregnant_woman",
    // "photo_camera",
    // "star",
    // "format_list_bulleted",
    // "navigate_next",
    // "extension",
    // "thumbs_up_down",
    // "hdr_weak",
    // "text_fields",
    // "kitchen",
    // "visibility_off",
    // "notifications_none",
    // "cloud_circle",
    // "rowing",
    // "edit",
    // "fullscreen_exit",
    // "format_list_numbered",
    // "wc",
    // "looks_6",
    // "brightness_auto",
    // "local_see",
    // "tonality",
    // "stay_primary_landscape",
    // "keyboard_arrow_right",
    // "do_not_disturb",
    // "beach_access",
    // "airline_seat_flat_angled",
    // "airline_seat_legroom_extra",
    // "hdr_strong",
    // "sort_by_alpha",
    // "format_line_spacing",
    // "my_location",
    // "slow_motion_video",
    // "timer_10",
    // "vertical_align_top",
    // "hourglass_full",
    // "content_paste",
    // "local_hospital",
    // "adjust",
    // "restaurant_menu",
    // "looks",
    // "looks_one",
    // "settings_cell",
    // "equalizer",
    // "clear_all",
    // "format_align_justify",
    // "room_service",
    // "verified_user",
    // "filter_list",
    // "input",
    // "settings_backup_restore",
    // "format_indent_decrease",
    // "nature_people",
    // "sync_disabled",
    // "theaters",
    // "view_module",
    // "border_style",
    // "settings_bluetooth",
    // "computer",
    // "airport_shuttle",
    // "attach_file",
    // "blur_on",
    // "language",
    // "keyboard_voice",
    // "portable_wifi_off",
    // "golf_course",
    // "fitness_center",
    // "vignette",
    // "contact_mail",
    // "phonelink_setup",
    // "delete_forever",
    // "videogame_asset",
    // "local_convenience_store",
    // "texture",
    // "delete",
    // "subdirectory_arrow_right",
    // "router",
    // "phone_bluetooth_speaker",
    // "phone",
    // "done_all",
    // "view_agenda",
    // "camera_alt",
    // "g_translate",
    // "no_sim",
    // "announcement",
    // "people_outline",
    // "sync",
    // "call",
    // "rotate_right",
    // "cloud_off",
    // "web",
    // "remove_red_eye",
    // "short_text",
    // "reorder",
    // "local_offer",
    // "sentiment_neutral",
    // "format_size",
    // "delete_sweep",
    // "local_grocery_store",
    // "settings_overscan",
    // "restore",
    // "brightness_1",
    // "signal_cellular_null",
    // "enhanced_encryption",
    // "toc",
    // "add_a_photo",
    // "nature",
    // "featured_play_list",
    // "grain",
    // "hourglass_empty",
    // "queue_play_next",
    // "share",
    // "add_box",
    // "album",
    // "vpn_lock",
    // "hd",
    // "get_app",
    // "burst_mode",
    // "gps_fixed",
    // "schedule",
    // "autorenew",
    // "subway",
    // "sort",
    // "storage",
    // "import_export",
    // "folder_open",
    // "settings_brightness",
    // "image_aspect_ratio",
    // "remove",
    // "pageview",
    // "explicit",
    // "brightness_3",
    // "undo",
    // "lock_outline",
    // "business",
    // "tablet_android",
    // "event_seat",
    // "sd_card",
    // "local_airport",
    // "replay_10",
    // "description",
    // "filter",
    // "insert_link",
    // "cast_connected",
    // "person_pin",
    // "airline_seat_recline_normal",
    // "comment",
    // "timeline",
    // "check_box",
    // "border_bottom",
    // "settings_power",
    // "stop_screen_share",
    // "event_note",
    // "network_check",
    // "insert_comment",
    // "assignment_late",
    // "reply_all",
    // "unfold_less",
    // "tune",
    // "linked_camera",
    // "pets",
    // "laptop",
    // "mood_bad",
    // "weekend",
    // "add_alert",
    // "call_merge",
    // "brightness_2",
    // "add_to_queue",
    // "perm_phone_msg",
    // "scanner",
    // "add_circle",
    // "notifications",
    // "featured_video",
    // "turned_in_not",
    // "add_to_photos",
    // "screen_share",
    // "local_parking",
    // "cloud",
    // "shuffle",
    // "flash_auto",
    // "error",
    // "date_range",
    // "control_point_duplicate",
    // "airline_seat_legroom_reduced",
    // "motorcycle",
    // "format_bold",
    // "drag_handle",
    // "phone_paused",
    // "brightness_6",
    // "pause",
    // "format_shapes",
    // "arrow_forward",
    // "view_week",
    // "flip_to_back",
    // "exposure",
    // "next_week",
    // "forward",
    // "flip",
    // "format_clear",
    // "bookmark",
    // "help",
    // "play_circle_filled",
    // "photo_filter",
    // "battery_full",
    // "more_vert",
    // "assistant_photo",
    // "settings_applications",
    // "tablet",
    // "slideshow",
    // "stay_primary_portrait",
    // "lightbulb_outline",
    // "sim_card_alert",
    // "chrome_reader_mode",
    // "done",
    // "format_color_fill",
    // "airline_seat_legroom_normal",
    // "tablet_mac",
    // "camera_front",
    // "forward_30",
    // "brightness_7",
    // "help_outline",
    // "pie_chart_outlined",
    // "sync_problem",
    // "menu",
    // "expand_less",
    // "poll",
    // "file_upload",
    // "play_arrow",
    // "backspace",
    // "keyboard_tab",
    // "format_paint",
    // "assignment_returned",
    // "web_asset",
    // "favorite_border",
    // "high_quality",
    // "spa",
    // "border_color",
    // "mouse",
    // "highlight_off",
    // "radio_button_checked",
    // "block",
    // "battery_unknown",
    // "photo_library",
    // "location_on",
    // "view_column",
    // "person_add",
    // "offline_pin",
    // "filter_8",
    // "zoom_out",
    // "fiber_new",
    // "label_outline",
    // "streetview",
    // "vibration",
    // "phonelink_ring",
    // "brightness_5",
    // "local_hotel",
    // "battery_charging_full",
    // "hdr_off",
    // "grid_off",
    // "history",
    // "switch_video",
    // "gavel",
    // "folder",
    // "alarm",
    // "speaker_group",
    // "local_bar",
    // "group_work",
    // "open_with",
    // "vertical_align_bottom",
    // "fingerprint",
    // "signal_wifi_4_bar",
    // "laptop_windows",
    // "timer",
    // "gamepad",
    // "cached",
    // "settings_input_component",
    // "radio_button_unchecked",
    // "devices_other",
    // "multiline_chart",
    // "assessment",
    // "all_out",
    // "timer_3",
    // "photo",
    // "question_answer",
    // "remove_circle",
    // "print",
    // "local_play",
    // "border_top",
    // "unarchive",
    // "pin_drop",
    // "open_in_new",
    // "shopping_basket",
    // "airline_seat_flat",
    // "accessibility",
    // "call_end",
    // "brightness_4",
    // "star_half",
    // "new_releases",
    // "access_alarms",
    // "loyalty",
    // "smoking_rooms",
    // "filter_9",
    // "vpn_key",
    // "insert_invitation",
    // "keyboard_capslock",
  ];
  return icons.map((svg) => (
    <IconButton onClick={() => handleButtonClick(svg)} key={svg}>
      <i className="material-icons">{svg}</i>
    </IconButton>
    // use Divider to seperate rows
  ));
};
export default IconList;
